/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_anybar.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "fakefullscreenclient.c"
#include "fullscreen.c"
#include "inplacerotate.c"
#include "moveresize.c"
#include "movestack.c"
#include "placemouse.c"
#include "push_no_master.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "switchcol.c"
#include "vanitygaps.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

