/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_anybar.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "moveresize.h"
#include "movestack.h"
#include "placemouse.h"
#include "push_no_master.h"
#include "rotatestack.h"
#include "scratchpad.h"
#include "switchcol.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

